### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by HoYin1600p** [BONNePlayground/VaultHuntersExtraCommands#1]
Allow server operators to add names to a list via command. 

Names on the list are given permission to tick freeze vaults while not being server operators. 

Add command /pause (or even /p if that is an option) as a toggle for members named in above mentioned list to be able to tick freeze and unfreeze the vault they are in currently. 

Intent is for people who may be pulled away from the game at a moments notice to be able to pause their vault while on a multiplayer server. The simplest method to pause is the best method, however keeping the mod server side limits this somewhat.

**Comment by BONNe** [comment]
done , will be available when I finish other stuff :D
